In [1]:
#phyton'da her şey objedir. Olayları kasmamak adına ve küçük bir eforla konuları çözmek için numpy array başvururuz.
number=15
type(number)

int

In [2]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [4]:
my_list=[1,2,3]
type(my_list)

list

In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
#numpy veri tipini daha basit ,listeler olarak tutar **numpy array**

In [ ]:
#pip install numpy

In [1]:
import numpy as np

In [3]:
type1=np.array([1,2,3,4])
type1.dtype


dtype('int32')

In [2]:
np.array([1,2,3,4],dtype=np.float_) #float çevirdim

array([1., 2., 3., 4.])

In [5]:
np.array([1,2,3,4],dtype=np.int_)

array([1, 2, 3, 4])

Dimensions and Shapes

In [6]:
my_array=np.array([
    [1,2,3],
    [4,5,6]
])

In [7]:
my_array.shape #shape
#output 2 row 3 column

(2, 3)

In [8]:
my_array.ndim #boyut

2

In [9]:
my_array.size #kaç tane kutucuk

6

3 boyut

In [10]:
my_array3=np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,6],
        [3,2,1]
    ]

])

In [12]:
my_array3.ndim #boyut

3

In [13]:
my_array3.shape

(2, 2, 3)

In [14]:
my_array3.size #kaç tane kutucuk

12

indexing and slicing

In [16]:
my_array=([1,2,3],[4,5,6])

In [17]:
my_array=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
my_array[1]

array([4, 5, 6])

In [20]:
print(my_array[1][0])
print(my_array[1,0]) #same


4
4


In [21]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
my_array[:2,:2]

array([[1, 2],
       [4, 5]])

In [23]:
my_array[1]=np.array([10,10,10]) #yeni bir yapı ekledim
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [25]:
my_array[2]=99
my_array #direkt değiştirebiliriz

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [31]:
my_array=np.arange(0,12)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
my_array.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.arange(1,10.1,2) #tek bir değeri float girdik diye diğerleri de float dönüşür

array([1., 3., 5., 7., 9.])

In [34]:
my_array.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [39]:
print(np.zeros(5))
np.zeros((5,2))

[0. 0. 0. 0. 0.]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
print(np.ones((2,5)))
np.ones((2,5,3)) #3 dimensions

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.eye(5,3) #eşit boyutlarda 1,0. ilk 3 'e diagonal 1 at diyor

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
my_array=np.random.random((5,2)) #random bir modül. onu çağırıp random etiketliyoruz
my_array

array([[0.00374172, 0.91809874],
       [0.34435227, 0.62462276],
       [0.23252634, 0.15342465],
       [0.62817064, 0.87788311],
       [0.9998698 , 0.76396774]])

In [48]:
np.random.randint(100,size=(5,5))

array([[45, 92, 54, 72, 76],
       [27, 39, 97, 58, 13],
       [77, 29, 83, 99, 50],
       [91, 94, 51, 23, 99],
       [94, 66, 18, 89, 22]])

In [51]:
np.linspace(1,10,5) #z koordinatı kaç tane istediğimizi kullanırız.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#any()
#all()
#full()
#concatenate() #phyton listesi ve array birleştirir.

In [54]:
np.any([1,5,10])

True

In [55]:
array1=np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
np.concatenate([array1,array1],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

Statistics

In [60]:
array1=np.arange(0,10)
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
print(array1.sum())
print(array1.mean())
print(array1.std())
print(array1.var())

45
4.5
2.8722813232690143
8.25


In [65]:
print(array1.sum(axis=1)) #row
print(array1.sum(axis=0)) #column

[10 35]
[ 5  7  9 11 13]


In [66]:
array1+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
array1 #yukarıfdaki işlemler ana array i etkilemedi. atama yapmadığımız için

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
array1+=10
array1 #eşitleme yapıp atama yaptığımız için ana veriyi etkiledi.

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
array1 #Ana veri

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Boolean Arrays

In [70]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [72]:
print(a[0],a[-1]) #doğrudan eleman alabilmek için
a[[0,-1]] #array olarak aldım

0 3


array([0, 3])

In [73]:
a[[True,False,False,True]]  #array([0, 1, 2, 3])

array([0, 3])

In [75]:
print(a>=2) #array([0, 1, 2, 3])
a[a>=2]

[False False  True  True]


array([2, 3])

In [76]:
a.mean()

1.5

In [79]:
print(a[a>a.mean()])
a[~(a>a.mean())] #not ifadesi

[2 3]


array([0, 1])

In [80]:
#numpy'da and or gibi ifadeler kullanılmaz onun yerine simgeler kullanılır.
a[(a==0)|(a==1)]   #or

array([0, 1])

In [81]:
a[(a<=2)&(a%2==0)]  #and

array([0, 2])

-100'e rastgele tam sayılardan oluşan ,3'e 3 bir matris.


-30'dan büyük olanları boolean yöntemi ile filtrele

In [86]:
#Task1
#100'e rastgele tam sayılardan oluşan ,3'e 3 bir matris.
task1=np.random.randint(100,size=(3,3))
print(task1)

#task2
#30'dan büyük olanları boolean yöntemi ile filtrele
print([task1>30])  # işlemleri boolean olarak arka planda çalıştırdığımız için bu şekilde de kullanırız.


[[13 39 43]
 [23 11 31]
 [46 76 96]]
[array([[False,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])]


In [90]:
my_array=np.array([0,1,2,3,4,5,6,7,8,9])
array_1=my_array.reshape(5,2)
array_2=my_array.reshape(2,5)
print(array_1)
print(array_2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [91]:
np.dot(array_1,array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [92]:
array_2.T #Transpose

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [94]:
import sys
sys.getsizeof(10)

28

In [96]:
sys.getsizeof(1000*100)

28

In [97]:
np.dtype(int).itemsize

4

In [98]:
np.dtype(np.int8).itemsize

1

In [99]:
np.dtype(float).itemsize #float ve int farklı

8

In [100]:
sys.getsizeof([1,2,3])

120

In [102]:
np.array([1,2,3]).nbytes

12

In [103]:
my_list=list(range(10000))
my_array=np.arange(10000)

In [107]:
%time np.sum(my_array**2)

CPU times: total: 0 ns
Wall time: 0 ns


-1724114088

In [106]:
%time sum(number**2 for number in my_list)

CPU times: total: 15.6 ms
Wall time: 8.99 ms


333283335000